config/routes.rb
Hallieandamiel::Application.routes.draw do
  resources :tags do
    resources :photos
  end

  resources :photos do |pho| # sho
    resources :tags
    collection do
      get :unapproved
      get :duplicates
      post :approve
    end
  end

  match "/categories", :to => 'tags#index' # Because tags is a scary word.
  match "/albums", to: 'tags#index', as: 'albums' # Because tags is a scary word.

  match "/thanks", to: 'photos#thanks', as: 'thank_you' # Because shut up REST is why

  root :to => 'tags#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  default_scope where(:deleted_at => nil)

  paginates_per 10

  has_many :taggings
  has_many :tags, :through => :taggings

  has_attached_file :photo, :styles => { :full => "900x960>", :thumbnail => "100x100#" },
    :storage => :s3,
    :s3_credentials => {
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      bucket: 'mcgeefamilyreunion',
    },
    bucket: 'mcgeefamilyreunion',
    :s3_headers => {'Expires' => 1.year.from_now.httpdate }

  validates_attachment_file_name :photo, :matches => [/png\Z/i, /jpe?g\Z/i, /gif\Z/i]
  # do_not_validate_attachment_file_type :photo

  scope :approved, where(:approved => true)
  scope :unapproved, where(:approved => false)

  after_save :tag_uploader

  validates_presence_of :photo
  validates_format_of :uploader_email, :with => /^\w(\.?[\w-])*@\w(\.?[\w-])*\.[a-z]{2,6}$/i, :allow_blank => true

  def sanitized_uploader_name
    uploader_name
  end

  def tag_uploader
    if uploader_name.present?
      t = Tag.find_or_create_by_tag_and_category(sanitized_uploader_name, 'user')
      t.taggings.create(photo: self) unless tags.include?(t)
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings
  has_many :photos, through: :taggings

  scope :people, where(category: 'person').order('tag ASC')
  scope :other, where(category: nil).order('tag ASC')

  def photographer?
    category == 'user'
  end

  def person?
    category == 'person'
  end

  def to_s
    if photographer?
      "Photographer: #{tag}"
    else
      tag
    end
  end

  def random_photo
    @random_photo ||= photos.offset(rand(photos.count)).first
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  
  belongs_to :photo
  belongs_to :tag
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  USER_NAME, PASSWORD = "palma", "isthatso"

  before_filter :authenticate
  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == USER_NAME && password == PASSWORD
    end
  end

end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  USER_NAME, PASSWORD = "amiel", "andhallie"

  before_filter :authenticate, :only => [ :edit, :unapproved, :approve, :duplicates, :destroy ]
  before_filter :find_tag

  protect_from_forgery :except => [:create]

  def index
    @photos = Photo.approved.page(params[:page] || 1).per(42)
  end

  def new
    @photo = Photo.new
  end

  def show
    @photo = Photo.find(params[:id])
    # @tag_for_form = @photo.tags.new

    if @photo
      # Get the next and previous photos in this set
      @photos = (@tag.try(:photos) || Photo).approved.all
      index = @photos.index(@photo)
      if index
        @previous_photo = @photos[index - 1] if index > 0
        @next_photo = @photos[index + 1]
      end
    end
  end

  def create
    @photo = Photo.new(params[:photo])
    @photo.approved = true
    @photo.uploader_ip = request.remote_ip

    if @photo.save then
      flash[:notice] = 'Awesome, your photo has been uploaded! Got any more?'
    else
      flash[:notice] = 'Unfortunately, there was a problem uploading that photo.'
    end

    respond_to do |format|
      format.html {
        # This is to pre-populate the next photo upload.
        # Only used when Uploadify horks
        @photo = Photo.new(:uploader_name => params[:photo][:uploader_name], :uploader_email => params[:photo][:uploader_email])
        render :new
      }
      format.js {
        if @photo.valid? then
          render :text => true.to_json;
        else
          render :text => @photo.errors.full_messages.to_json, :status => '200' # BUG: this should be a status, but uploadify makes it impossible. :[
        end
      }
    end
  end

  def unapproved
    @photos = Photo.unapproved.page(params[:page] || 1).per(100)
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def duplicates
    counts = Photo.count :group => 'photo_file_name'
    # @duplicates = counts.select { |file_name, count| count > 1 }.
    #               collect { |file_name, count| Photo.all :conditions => { :photo_file_name => file_name } }

    @duplicates = counts.select { |file_name, count| count > 1 }
    @duplicates.each { |file_name, count|
      duplicate = Photo.all :conditions => { :photo_file_name => file_name }

      # Make sure the duplicates have the same file size
      duplicate = duplicate.select { |d| d.photo_file_size == duplicate.first.photo_file_size }
      next if duplicate.size < 2

      @duplicate = duplicate
    }
  end

  def update
    @photo = Photo.find(params[:id])

    if @photo.update_attributes(params[:photo]) then
      redirect_to @photo
    else
      render :edit
    end
  end

  def approve
    params[:approve].each do |id|
      Photo.find(id).update_attribute :approved, true
    end

    redirect_to unapproved_photos_path
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.update_attribute :deleted_at, Time.current
      flash[:notice] = "Deleted photo ##{ params[:id] }"
    else
      flash[:notice] = "Sorry, not saved: #{ @photo.errors.full_messages.join ', ' }"
    end
    redirect_to action: :duplicates
  end

  private
    def authenticate
      authenticate_or_request_with_http_basic do |user_name, password|
        user_name == USER_NAME && password == PASSWORD
      end
    end

    def find_tag
      @tag = Tag.find(params[:tag_id]) if params[:tag_id]
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  CATEGORY_SORT_MAP = { nil => 1, 'user' => 0, 'person' => 2 }

  def index
    if params[:photo_id] then
      @tags = Photo.find(params[:photo_id]).tags
    elsif params[:term] then
      @tags = Tag.where(['tag like ?', params[:term] + '%'])
    else
      @tags = Tag.all
    end

    @categories = @tags.group_by(&:category).sort_by { |category, tags|
      CATEGORY_SORT_MAP[category]
    }

    session[:most_recent_tag] = nil

    respond_to do |format|
      format.html {}
      format.json { render :json => @tags.collect(&:tag) }
    end
  end

  def show
    @tag = Tag.find(params[:id])
    @photos = @tag.photos.approved.page(params[:page] || 1).per(42)

    session[:most_recent_tag] = @tag.id
  end

  def create
    @tag = Tag.find_or_create_by_tag(params[:tag][:tag]) # BIG BUG: case-insensitive

    if params[:photo_id] then
      @photo = Photo.find(params[:photo_id])
      @tagging = Tagging.create({
        :tag => @tag,
        :photo => @photo,
      })

      redirect_to @photo
    else
      redirect_to tags_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tags_helper.rb
module TagsHelper
  def title_for_category(category)
    # TODO: I18n
    case category
    when 'user'
      'By Photographer'
    when 'person'
      'By Person'
    else
      'By Category'
    end
  end
end

app/views/application/_breadcrumbs.html.erb
<%= link_to 'Photos', root_path %>

<% if @tag %>&rsaquo; <%= link_to @tag, @tag %> <% end %>

app/views/details/_alaska.html.erb
<h3>Lodging</h3>

<p>
  There are many hotels and bed and breakfasts in Fairbanks. Here are a few to get you started (more to be posted soon).
</p>

<ul>
  <li><a href="http://www.pikeslodge.com/">Pike&rsquo;s Lodge</a> (some of Amiel&rsquo;s family is staying here)</li>
  <li><a href="http://guide.alaskatravel.com/listings/quilted-with-a-view-bed-breakfast.html">Quilted with View</a> (near the reception site)</li>
  <li><a href="http://www.riversedge.net/">River&rsquo;s Edge</a></li>
</ul>

<p>&nbsp;</p>

<p>Furthermore, there will be plenty of camping space at Hallie's parents place.</p>

<p>Also, please note that there will be daylight almost all night.</p>


<h3>Travel</h3>

<dl>
  <dt>Airplane</dt>
  <dd>
    <p>
      This will be the quickest way. As of this writing (early February), you can fly from Seattle to Fairbanks round trip for $700.
    </p>

    <p>
      The cheapest way to fly to Fairbanks would be to sign up for an Alaska Airlines credit card. They charge an annual fee of $75, but you get 25,000 miles on sign up, which is enough for a round trip flight to Alaska. You also get a companion ticket, which allows you to buy a second ticket for $99.
    </p>

    <p>
      Another option would be to find someone else that is coming who already has a companion ticket.
    </p>
  </dd>

  <dt>Drive</dt>
  <dd>
    <p>
      From Seattle to Fairbanks is about 2,200 miles of beautiful scenery. It could take 2 days if you drive day and night, but more realistically, it&rsquo;s a 4-day drive.
    </p>

    <p>Let us know if you plan to drive and are interested in sharing a seat.</p>

    <p>Craigslist often has people looking for a companion for the long drive. Check Craigslist for <a href="http://fairbanks.craigslist.org/rid/">Fairbanks</a>, <a href="http://anchorage.craigslist.org/rid/">Anchorage</a>, or <a href="http://seattle.craigslist.org/rid/">Seattle</a>.
  </dd>

  <dt>Ferry</dt>
  <dd>
    <p>
      The <a href="http://www.dot.state.ak.us/amhs/index.shtml">Alaska Marine Highway</a> has a 6-day ferry to Anchorage (almost), from which you could take a train to Fairbanks.
    </p>

    <p>There is also a 4-day ferry to Haines, AK, which is a 640 mile (12 hour) drive from Fairbanks.</p>
  </dd>
</dl>

app/views/details/_basic_information.html.erb
<dl>
  <dt>When</dt>
  <dd>July 23rd, 2011</dd>

  <dt>Where</dt>
  <dd><a href="http://goo.gl/maps/AGv7" rel="external">Fairbanks, Alaska</a></dd>


  <dt>Hey, that&rsquo;s a long ways away!</dt>
  <dd>You should come anyway because it&rsquo;ll be a really fun gathering with lots of really cool people and Alaska is awesome. However, we are planning to have another celebration in the Seattle area for those who can&rsquo;t make it all the way to Alaska and for those who want to party twice as much.</dd>

</dl>

app/views/details/_itinerary.html.erb
<dl>
  <dt>Thursday</dt>
  <dd>
    The New Old Time Chautauqua will be doing a parade during the day, and a show Thursday evening at <a href="#pioneer_park">Pioneer Park</a>. Y&rsquo;all should come!
    <ul>
      <li><strong>12:00</strong> Parade</li>
      <li><strong>1-3</strong> Workshops</li>
      <li><strong>7:30</strong> Show</li>
    </ul>
  </dd>

  <dt>Friday</dt>
  <dd>
    <ul>
      <li><strong>7:00</strong> Family Dinner</li>
    </li>
  </dd>

  <dt>Saturday</dt>
  <dd>
    <ul>
      <li><strong>2:30</strong> Ceremory on <a href="#marriage_site">Murphy Dome</a></li>
      <li><strong>4:00</strong> Reception at the <a href="#mushers_hall">Mushers Hall</a> to follow</li>
    </ul>
  </dd>

  <dt>Sunday</dt>
  <dd>Picnic on a Tanana River sandbar</dd>

</dl>

<h2>Map</h2>
<p>
  Jump to:
  <a href="#marriage_site">Ceremony</a> |
  <a href="#mushers_hall">Reception &amp; Family Dinner</a> |
  <a href="#mcgee_house">Camping</a>
</p>
<p>
  Chautauqua:
  <a href="#pioneer_park">Parade &amp; Show</a> |
  <a href="#notc_camp">Camp</a>
</p>
<p>
  Activities:
  <a href="#chena_hot_springs">Hot Springs</a> |
  <a href="#hot_licks">Ice Cream</a>
</p>
<div id="map"></div>

app/views/details/_more_information.html.erb
<dl>
  <dt>The Ceremony</dt>
  <dd>
    <p>We will assemble on Murphy Dome at 2:30 to witness and support our union (Murphy Dome is one of the highest peaks in the Fairbanks area).</p>

    <p>
      The ceremony will be outside, so be prepared for wind, sun, and possibly light rain (if it rains too hard we'll go inside).
      Also, wear comfortably supportable shoes as there is a bit of a walk; high heels are not recommended.
      That said, you are probably still wondering, &ldquo;what should I wear?&rdquo; Well, all I can say is <em>express yourself</em>.
    </p>

    <p>At some point we will have a &ldquo;tossup&rdquo; (where everyone throws something into the air). Bring something to throw (hats, juggling props, small children, rubber ducks, etc).</p>
  </dd>

  <dt>Celebrating...</dt>
  <dd>
    <!-- <p>
      We&rsquo;d like the weekend to be a community gathering. Plan to be here Friday night to join in the fun as you share your non-material gifts with us in the form of a song, dance, poem, skit, etc.
    </p> -->

    <p>There will be a reception at the <a href="#itinerary">Mushers Hall</a> after the ceremony.</p>
    <p>At the reception there will be appetizers, dinner, and a contra-dance. Bring <strong>dancing shoes</strong> and <strong>instruments</strong>.</p>
  </dd>

  <dt>Gifts &amp; Sharing</dt>
  <dd>Due to the fact that we live on a boat and therefore cannot acquire any more material possessions (or we will not have space for sleeping), the gift of your presence is enough. However, if you just can&rsquo;t help yourself, contributions to our honey moon travel fund will be graciously accepted as well.</dd>


  <!-- <p>
    If you are coming from out of town, there are plenty of things to do aside from watching us get married, and almost as fun. This is the excuse you need to add Alaska to your list of states you’ve been to.
  </p> -->
</dl>

app/views/details/_rsvp.html.erb
<script type="text/javascript">var host = (("https:" == document.location.protocol) ? "https://secure." : "http://");document.write(unescape("%3Cscript src='" + host + "wufoo.com/scripts/embed/form.js' type='text/javascript'%3E%3C/script%3E"));</script>

<script type="text/javascript">
  var z7x4a3 = new WufooForm();
  z7x4a3.initialize({
    'userName':'hallieandamiel',
    'formHash':'z7x4a3',
    'autoResize':false,
    'height':'1250'});
  z7x4a3.display();
</script>

app/views/details/index.html.erb
<h2 class="js-hide">Thank You</h2>
<p>Thank you everyone for coming and making our special day so awesome!</p>

<p>If you took any pictures, and feel like sharing them, please check back here soon to upload your favorite photos.</p>

<p>&mdash; Amiel and Hallie</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>The McGee Family Reunion</title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript">
    document.getElementsByTagName('html')[0].className += 'js';
  </script>

  <link href='http://fonts.googleapis.com/css?family=Neucha|Josefin+Sans+Std+Light' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Tienne' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" href="/css/screen.css" type="text/css" />
  <link rel="stylesheet" href="/css/chosen.css" type="text/css" />

  <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!--[if lte IE 8]>
    <script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js" type="text/javascript"></script>
  <![endif]-->

</head>
<body>
  <img class="bg" src="http://mcgeefamilyreunion.s3.amazonaws.com/photos/photos/000/000/031/full/DSC03401.jpg" />
  <div id="wrapper">

    <header class="<%= 'hide' if params[:hide_header] %>">
      <h1>The McGee Family Reunion</h1>
      <nav>
        <ul>
          <li><a href="<%= albums_path %>" class="current">Photos</a></li>
        </ul>
      </nav>
    </header>

    <% if flash[:notice] %>
    <section class="flash notice">
      <%= flash[:notice] %>
    </section>
    <% end %>

    <section class="body" id="<%=controller.controller_name%>_<%=controller.action_name%>">
      <%= yield %>
    </section>

  </div>

  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>

  <script type="text/javascript" charset="utf-8" src="/javascripts/chosen.jquery.min.js"></script>
  <script type="text/javascript" charset="utf-8" src="/javascripts/application.js"></script>
  <div></div> <%# This helps the jQuery ready event. %>

  <%= yield :footer %>
</body>
</html>

app/views/photos/_photo.erb
<li>
  <%= link_to image_tag(photo.photo.url(:thumbnail)), [@tag, photo] %>
</li>

app/views/photos/duplicates.html.erb
<h2>Duplicate Photos</h2>

<% if @duplicate.nil? %>
  <div class="no-content">
    No duplicates were found.
  </div>
<% else %>

  <% @duplicate.each do |photo| %>

    <%= image_tag photo.photo.url(:full), class: 'full_photo' %>
    <%= link_to 'Delete this photo', photo_path(photo), method: :delete, confirm: 'Are you sure you want to delete this photo?' %>

    <section class="metadata">

      <section class="tags">
        <h4>Tags</h4>
        <ul class="tags">
        <% photo.tags.each { |tag| %>
          <li class="tag" id="<%=dom_id(tag)%>"><%= tag %></li>
        <% } %>
        </ul>
      </section>

      <dl>
        <dt>ID</dt>
        <dd><%= photo.id %></dd>

        <dt>File Name</dt>
        <dd><%= photo.photo_file_name %></dd>

        <dt>Uploader name</dt>
        <dd><%= photo.uploader_name %></dd>

        <dt>Uploader ip</dt>
        <dd><%= photo.uploader_ip %></dd>

        <dt>File size</dt>
        <dd><%= photo.photo_file_size %></dd>

        <dt>Uploaded at</dt>
        <dd><%= photo.created_at %></dd>
      </dl>
    </section>
  <% end %>
<% end %>

app/views/photos/edit.html.erb
<%=semantic_form_for @photo, :html => { :multipart => true } do |f| %>
	<ul class="errors">
	</ul>
	<%=f.inputs do %>
		<%=f.input :uploader_name, label: 'Uploader Name' %>
		<%=f.input :uploader_email, label: 'Uploader Email' %>
		<%=f.input :approved %>
	<% end %>
	
    <%= f.buttons do %>
      <button type="submit">Finish and Upload</button>
    <% end %>
<% end %>

app/views/photos/index.html.erb
<h2>Photos</h2>

<ul class="thumbnails">
  <%= render @photos %>
</ul>                                                                      

<%= paginate @photos %>  

<%= link_to 'Add Your Photos', new_photo_path, class: 'button' %>

app/views/photos/new.html.erb
<h2>Add Your Photos</h2>

<p>Once we add your photos, everyone will be able to enjoy them.</p>

<%=semantic_form_for @photo, :html => { :multipart => true } do |f| %>
	<ul class="errors">
	</ul>
	<%=f.inputs do %>
		<%=f.input :uploader_name, label: 'Your First Name', hint: "We want to make sure you get credit for all of your snazzy photography work" %>
		<%=f.input :uploader_email, label: 'Your Email', hint: "Don't worry, it's just between us and you" %>

		<%=f.input :photo, :hint => "Browse for the photos you'd like to add" %>
	<% end %>

    <%= f.buttons do %>
      <button type="submit">Finish and Upload</button>
    <% end %>
<% end %>

<% content_for :footer do %>
	<link href="/css/uploadify.css" type="text/css" rel="stylesheet" />
	<script type="text/javascript" src="/javascripts/jquery.uploadify.js"></script>
	<script type="text/javascript">
	var upload_errors = [];

	$(function() {
	  $('#photo_photo').uploadify({
	    'swf'  : '/uploadify.swf',
	    'uploader'    : <%=raw photos_path(:format=>'js').to_json %>,
	    'cancelImage' : '/images/uploadify-cancel.png',
		'checkExisting': false,
		'removeCompleted': true,
	    'auto'      : false,
		'requeueErrors' : false,
		'multi' : true,
		'buttonText' : 'Select Photos',
		'buttonImage': '',
		'fileObjName' : 'photo[photo]',
		'postData'	: {
			'authenticity_token': <%=raw form_authenticity_token.to_json %>
		},
		'onQueueComplete': function() {
			if (upload_errors.length == 0) {
				document.location = <%= raw thank_you_path.to_json %>;
			} else {
				$('#new_photo').find('.errors').html('');
				for(i in upload_errors) {
					$('#new_photo').find('.errors').append('<ul>'+upload_errors[i]+'</ul>');
				}
				$('#new_photo').find('.commit').show(); // TODO: enable instead
			}
		},
		'onUploadSuccess': function(file, messages, response) {
			var response_object = jQuery.parseJSON(messages);
			if (response_object != true) { // TODO: typeof
				upload_errors = response_object;
				// TODO: requeue eventually
			}
		}
	  });

		$('#new_photo').submit(function() {

			upload_errors = [];

			$('#photo_photo').uploadifySettings('postData',{
					'photo[uploader_name]' : $('#photo_uploader_name').val(),
					'photo[uploader_email]' : $('#photo_uploader_email').val()
			});

			$('#photo_photo').uploadifyUpload();
			// TODO: disable the buttons here, but only if there's photos in the queue
			return false;
		});

	});
	</script>
<% end %>

app/views/photos/show.html.erb
<h2><%= render 'breadcrumbs' %>&rsaquo; View Photo</h2>

<div class="next"><%= link_to 'Next', polymorphic_path([@tag, @next_photo], hide_header: params[:hide_header], anchor: 'photos_show') if @next_photo %></div>
<div class="previous"><%= link_to 'Previous', polymorphic_path([@tag, @previous_photo], hide_header: params[:hide_header], anchor: 'photos_show') if @previous_photo %></div>

  <%= link_to_if @next_photo, image_tag(@photo.photo.url(:full), class: 'full_photo'), polymorphic_path([@tag, @next_photo], hide_header: params[:hide_header], anchor: 'photos_show') %>

<section class="metadata">

  <p class="download_full">
    Want a print? <%= link_to 'Download the full-sized version', @photo.photo.url %>.
  </p>

  <p>
    <% if params[:hide_header] %>
      <%= link_to 'show header', '?' %>
    <% else %>
      <%= link_to 'Hide header', '?hide_header=true' %>
    <% end %>
  </p>

  <section class="tags">
    <ul class="tags">
      <% @photo.tags.reject { |tag| tag.new_record? }.each { |tag| %>
        <li class="tag" id="<%= dom_id(tag) %>"><%= link_to(tag, tag) %></li>
      <% } %>
    </ul>

    <%= semantic_form_for [@photo] do |f| %>
      <a href="#" id="tagging_toggle">Help us categorize this photo</a>
      <%= f.inputs do %>
        <%= f.input :tags, as: :select, multi: true, label: "Update Albums", collection: (Tag.other + Tag.people) %>
        <li id="tag_submit">
          <button type="submit">Update</button>
        </li>
      <% end %>
    <% end %>
  </section>

</section>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    $('form.photo ol').hide();

    $('#tagging_toggle').click(function(){
      $('form.photo ol').slideToggle();
      return false;
    });
  });
</script>

app/views/photos/thanks.html.erb
<h2>Thank you!</h2>

<p>Thanks for sharing your photos with everyone.</p>

app/views/photos/unapproved.html.erb
<h2>Photos</h2>

<%= form_tag '/photos/approve' do %>

  <ul class="thumbnails">
    <% for photo in @photos %>
      <li>
        <%= link_to image_tag(photo.photo.url(:thumbnail)), [@tag, photo] %>
        <%= check_box_tag 'approve[]', photo.id, true %>
      </li>
    <% end %>
  </ul>

  <%= submit_tag "Approve all selected photos" %>

<% end %>

<%= paginate @photos %>

app/views/tags/_tag.html.erb
<%- collection = tag.photos.approved.all -%>

<% if collection.size > 0 %>
  <li class="album">
    <%= link_to image_tag(collection.sample.photo.url(:thumbnail), alt: 'tag'), tag %>
    <%= link_to tag.tag, tag %>
  </li>
<% end %>

app/views/tags/index.html.erb
<p>If you took pictures, please share them with us here.</p>

<h2>Photo Albums</h2>

<% if @tags.size > 0 then %>
  <% @categories.each do |category, tags| %>
    <h4><%= title_for_category category %></h4>
    <ul class="thumbnails">
      <%= render tags.sort_by(&:tag) %>
    </ul>
  <% end %>
<% else %>
  <div class="no-content">Unfortunately, nobody's uploaded any photos yet. Why not <%= link_to 'upload your own?', new_photo_path %></div>
<% end %>
<%= link_to 'Add Your Photos', new_photo_path, class: 'button' %>

app/views/tags/show.html.erb
<h2><%= render 'breadcrumbs' %></h2>

<ul class="thumbnails">
  <%= render @photos %>
</ul>

<%= paginate @photos %>